<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-29T23:33:04 EDT" name="Default suite" finished-at="2022-05-29T23:33:41 EDT" duration-ms="37133">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.runners.Runner@2e6a8155]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2022-05-29T23:33:04 EDT" name="Default test" finished-at="2022-05-29T23:33:41 EDT" duration-ms="37133">
      <class name="com.runners.Runner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:com.runners.Runner@2e6a8155]" started-at="2022-05-29T23:33:04 EDT" name="setUpClass" finished-at="2022-05-29T23:33:05 EDT" duration-ms="988" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@23cd5d42]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.runners.Runner@2e6a8155]" started-at="2022-05-29T23:33:05 EDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2022-05-29T23:33:16 EDT" duration-ms="10568" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login Error Message"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login into salesforce application"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.runners.Runner@2e6a8155]" started-at="2022-05-29T23:33:16 EDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2022-05-29T23:33:28 EDT" duration-ms="11888" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login with valid user and valid password"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login into salesforce application"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [welcom to your free trial] but found [Getting Started]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [welcom to your free trial] but found [Getting Started]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.steps.StepDefinitionTC1andTc2.message_should_be(StepDefinitionTC1andTc2.java:97)
at ✽.message should be "welcom to your free trial"(file:///C:/Selenium/SalesForceCucumberWithPOM/src/test/resources/features/featurefileTC1andTc2.feature:24)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.runners.Runner@2e6a8155]" started-at="2022-05-29T23:33:28 EDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2022-05-29T23:33:41 EDT" duration-ms="13499" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Check Remember Me CheckBox"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login into salesforce application"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [welcom to your free trial] but found [Getting Started]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [welcom to your free trial] but found [Getting Started]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.steps.StepDefinitionTC1andTc2.should_be_displayed_on_username_field(StepDefinitionTC1andTc2.java:126)
at ✽."salesforce@tekarch.com" should be displayed on username field(file:///C:/Selenium/SalesForceCucumberWithPOM/src/test/resources/features/featurefileTC1andTc2.feature:38)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:com.runners.Runner@2e6a8155]" started-at="2022-05-29T23:33:41 EDT" name="tearDownClass" finished-at="2022-05-29T23:33:41 EDT" duration-ms="128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.runners.Runner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
